Better deserialization errors
input-output-hk/catalyst-toolbox pull request #153
Opened 2022-07-21 10:01 UTC by cameron1024

Replaces a few custom deserializers with manual `Deserialize` implementations (with descriptions of the format of the data for better error messages)

2022-07-28 09:23 UTC, Zeegomo requested changes

2022-07-28 09:23 UTC, Zeegomo commented on script.sh
> +cargo run --bin catalyst-toolbox ideascale import --api-token 3ff50be1-084c-47b1-9df5-53aa2e150099 --fund 8  --chain-vote-type private --output-dir . --threshold 450 --fund-goal "Create, fund and del
We probably don't need this?

2022-07-28 09:23 UTC, Zeegomo commented on catalyst-toolbox/src/ideascale/models/de/ada_rewards.rs
> +// fn deserialize_rewards<'de, D: Deserializer<'de>>(deserializer: D) -> Result<u64, D::Error> {
I guess this is not needed anymore?

2022-07-28 09:23 UTC, Zeegomo commented on catalyst-toolbox/src/ideascale/models/de/approval.rs
> +            _ => Ok(Approval::NotApproved),
nit: `"Approved"` would be parsed as `NotApproved` which is a bit counterintuitive, I think it's better to have this in lowercase before comparison

2022-07-28 09:26 UTC, cameron1024 commented on catalyst-toolbox/Cargo.toml
> +tracing-subscriber = "0.3"
I added it for debugging something, but I don't think it's strictly needed any more. Happy to remove, but I guess it probably doesn't make too much difference whether we use `tracing` or `log` :shrug:

2022-07-28 09:27 UTC, cameron1024 commented on script.sh
> +cargo run --bin catalyst-toolbox ideascale import --api-token 3ff50be1-084c-47b1-9df5-53aa2e150099 --fund 8  --chain-vote-type private --output-dir . --threshold 450 --fund-goal "Create, fund and del
Oops

2022-07-28 12:28 UTC, Zeegomo commented on .pre-commit-config.yaml
> +/nix/store/80r7admw5vnzl9zxhbznd1yqlfmajck1-pre-commit-config.json
should this be committed?

2022-08-10 09:17 UTC, Mr-Leshiy commented
need to update with the latest master :)

2022-08-19 02:06 UTC, saibatizoku approved these changes
tracing! awesome

2022-08-19 09:25 UTC, Mr-Leshiy approved these changes

2022-08-24 13:21 UTC, merged